name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'  # Replace 'x' with the actual minor/patch version

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: 🔨 Build Project
        run: |
          npm install --legacy-peer-deps
          npm run build -- --configuration=production --output-path=dist/browser

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/browser/  # Ensure this points to the 'browser' folder inside 'dist'
